spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logisticswarehousemanagement?serverTimezone=UTC&characterEncoding=UTF-8
    username: newuser
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

